# ==================================================================
# module list
# ------------------------------------------------------------------
# python        2.7    (apt)
# torch         latest (git)
# chainer       latest (pip)
# cntk          latest (pip)
# jupyter       latest (pip)
# mxnet         latest (pip)
# onnx          latest (pip)
# pytorch       0.4.1  (pip)
# tensorflow    latest (pip)
# theano        1.0.1  (git)
# keras         latest (pip)
# lasagne       latest (git)
# opencv        3.4.1  (git)
# sonnet        latest (pip)
# caffe         latest (git)
# caffe2        latest (git)
# ==================================================================

FROM ufoym/deepo:all-jupyter-py27-cpu

# ==================================================================
# shared volume , -v $(pwd):/home/project
# ------------------------------------------------------------------
RUN mkdir -p /home/project
WORKDIR /home/project



